polls/api/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from polls.api.views.polls import GetUser

router = routers.DefaultRouter()

# register routes
router.register(r'^', GetUser)


urlpatterns = [
    url(r'^', include(router.urls)),
]

polls/urls.py
from django.conf.urls import url
from polls.views.polls import PollView, VoteView

urlpatterns = [
    url(r'^$', PollView.as_view(), name="polls"),
    url(r'^(?P<id>[0-9]+)/$', VoteView.as_view(), name="question"),
    url(r'^(?P<id>[0-9]+)/vote$', VoteView.as_view(), name="vote"),
]

pollstar/urls.py
from django.contrib import admin
from django.conf.urls import include, url


urlpatterns = [

    #############   Web Routes   ########################
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^', include('polls.urls')),


    #############   API Routes   ########################
    url(r'^api/polls/', include('polls.api.urls')),

]

polls/models.py
from django.db import models
from django.contrib.auth.models import User


class Poll(models.Model):
    """
    Poll model
    """

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Question(models.Model):
    """
    Question model
    """

    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    question_text = models.CharField(max_length=200)
    total_voter = models.IntegerField(default=0)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    class Meta:
        pass


class Choice(models.Model):
    """
    Choice model for the question model
    """

    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    choice_text = models.CharField(max_length=200)

    total_vote = models.IntegerField(default=0)

    def getTotalVoteInPercentage(self):
        """
        Get total vote in percentage
        """

        if (self.total_vote != 0) and (self.question.total_voter != 0):
           return (self.total_vote / self.question.total_voter) * 100
        else:
            return 0

    def __str__(self):
        return self.choice_text

    class Meta:
        pass

polls/api/views/polls.py
from rest_framework import viewsets
from django.contrib.auth.models import User
from polls.api.serializers.user import UserSerializer

# Create your views here.
class GetUser(viewsets.ModelViewSet):
        queryset = User.objects.all().order_by('-date_joined')
        serializer_class = UserSerializer

polls/views/polls.py
from polls.models import Poll
from polls.models import Choice
from polls.models import Question
from django.contrib import messages
from django.views.generic import View
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


class PollView(View):
    """
    Poll view
    """

    def get(self, request):
        """
        Show polls list
        """

        polls = Poll.objects.all()
        paginator = Paginator(polls, 10)

        page = request.GET.get('page')

        try:
            polls = paginator.page(page)
        except PageNotAnInteger:
            polls = paginator.page(1)
        except EmptyPage:
            polls = paginator.page(paginator.num_pages)

        return render(request, 'index.html', {'polls': polls})


class VoteView(View):
    """
    Vote view
    """

    def get(self, request, id):
        """
        Show single poll
        """

        poll = get_object_or_404(Poll, id=id)

        context = {'poll': poll, 'id': id}

        return render(request, 'vote.html', context)


    def post(self, request, id):
        """
        Accept vote from voter
        """

        # count and store new voter
        for data in request.POST:
            if data != 'csrfmiddlewaretoken':
                totalvoter = Question.objects \
                                 .get(id=data) \
                                 .total_voter + 1

                Question.objects.filter(id=data) \
                    .update(total_voter=totalvoter)

        # Count and store up vote's for the all selected choice
        for data in request.POST:
            if data != 'csrfmiddlewaretoken':
                upvote = Choice.objects \
                             .get(id=request.POST[data]) \
                             .total_vote + 1

                Choice.objects \
                    .filter(id=request.POST[data]) \
                    .update(total_vote=upvote)

        messages.success(request, 'Your vote successfully submitted')

        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

polls/templates/index.html
{% extends 'layouts/default.html' %}

{% block content %}

    <div class="ui container">
        <div class="ui row">
            <div class="column 12">
                <h4>Available Polls...</h4>

                <div class="ui divided items">
                    {% for poll in polls %}
                      <div class="item">
                        <div class="ui tiny image">
                          <img src="http://faker.im/250x250">
                        </div>
                        <div class="middle aligned content">
                            <a href="{% url "question" poll.id %}">{{ poll.name }}</a>
                            <br>
                            <span>Created by - {{ poll.user }}</span>
                        </div>
                      </div>
                    {% endfor %}
                </div>

                <div class="ui mini pagination menu">
                    {% if polls.has_previous %}
                        <a  class="active item" href="?page={{ polls.previous_page_number }}">previous</a>
                    {% endif %}

                    <div class="disable item">
                        Page {{ polls.number }} of {{ polls.paginator.num_pages }}
                    </div>

                    {% if polls.has_next %}
                        <a class="item"  href="?page={{ polls.next_page_number }}">next</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

polls/templates/layouts/default.html
<!doctype html>
<html lang="en">
    <head>
        <title>Polls</title>

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.4/semantic.min.css">
    </head>

    <body>

        <!-- nav bar -->
        <div class="ui top menu">
            <div class="item">
                <h4>
                    <a href="/">Polls</a>
                </h4>
            </div>

            <a href="https://github.com/IftekherSunny/pollstar" class="item right">Github</a>
        </div>

        <!-- render child content -->
        {% block content %}
        {% endblock %}

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.4/semantic.min.js"></script>

        {% block scripts %}
        {% endblock %}
    </body>
</html>

polls/templates/vote.html
{% extends 'layouts/default.html' %}

{% block content %}

    <div class="ui container">
        <div class="ui row">
            <div class="column 12">

            {% if messages %}
                <div class="ui success message">
                  <i class="close icon"></i>
                  {% for message in messages %}
                      <div class="header">
                        {{ message }}
                      </div>
                  {% endfor %}
                </div>
            {% endif %}

                <h4>{{ poll.name }}</h4>

                <form action="{% url "vote" id %}" method="post">
                    {% csrf_token %}
                    <div class="ui form">
                        {% for question in poll.question_set.all %}
                            <div class="grouped fields">
                                <label for="fruit">{{ question.question_text }}</label>

                                {% for choice in question.choice_set.all %}
                                    <div class="field">
                                      <div class="ui radio checkbox">
                                        <input name="{{ question.id }}" value="{{ choice.id }}" checked="" tabindex="0" class="hidden" type="radio">
                                        <label>{{ choice.choice_text }}</label>
                                      </div>
                                    </div>
                                {% endfor %}
                            </div>
                        {% endfor %}
                    </div>

                    <div class="ui form">
                        <input type="submit" class="ui button green" value="Submit Your Vote">
                    </div>

                </form>


            </div>
        </div>
    </div>

{% endblock %}

{% block scripts %}
        <script>
            $('.ui.radio.checkbox').checkbox();

            $('.message .close')
              .on('click', function() {
                $(this)
                  .closest('.message')
                  .transition('fade')
                ;
              })
            ;
        </script>
{% endblock %}